### ISSUE TITLE
Hesap Silme bölümü hızlı açılma. 

### ISSUE THREAD

**Issue by UgurhanKazanci61** [seahindeniz/BrainlyTools_Extension#106]
Herhangi bir profile girdiğimizde 'Daha fazla göster' bölümüne tıklamadan açılıyor. 'Sil' bölümü de tıklamadan direkt açılabilir.

**Comment by UgurhanKazanci61** [comment]
Ayriyeten ban verme bölümü de direkt 48 saat ban olarak açılabilir.

**Comment by seahindeniz** [comment]
Her moderatör 48 saat ban kullanmadığından dolayı varsayılan olarak belirlemek mantıklı olmaz. Bildirimi kapatıyorum çünkü ana talep sonuçlandı.

Not every moderator applies 48 hours of ban on abusive users so it's not makes sense to set as default option. So I'm closing this this issue due to original feature has been added
