### ISSUE TITLE
A button to delete comments under a question

### ISSUE THREAD

**Issue by tom-rh** [seahindeniz/BrainlyTools_Extension#128]
### Example of button integration :

![Example of button integration](https://user-images.githubusercontent.com/64775524/82332861-3a6d7080-99e6-11ea-8cd8-d28cfc6c8f08.png)

### Details :

This button allows you to delete with one click all the comments present on a question.

This button addresses the concerns we are currently having with some users talking like in a chatroom.

**Comment by Mistystar4881** [comment]
I love this idea, it would be extremely useful.

**Comment by seahindeniz** [comment]
This request is related moderate panel on the moderate all page and also on the question page.
Brainly Tools will no longer have new features for the moderate all page and features will be marked as deprecated as well.

This feature has now implemented in the new moderate panel that we are using it on the new reported contents page.
In the future, when the new moderate panel is ready enough, the moderate panel on the question page will be replaced with the new moderate panel in order to use more enhanced features

**Comment by seahindeniz** [comment]
The feature has already in production. Available since #242 got closed
