### ISSUE TITLE
Number of page

### ISSUE THREAD

**Issue by Maxonvs** [seahindeniz/BrainlyTools_Extension#165]
**Is your feature request related to a problem? Please describe.**
Due to a recent bug on the reported answers section, we now have to use  chrome extension to show us an approximate number of reported issues according to the number of pages. However that method does not work with the comment option or whenever a filter is being used

**Describe the solution/idea you'd like**
Add a number of pages when filtering a certain content

**Describe expected outcome from your solution**
![image](https://user-images.githubusercontent.com/39934266/89595608-f2aaf800-d822-11ea-9d9e-09bf0c127c24.png)

**Comment by seahindeniz** [comment]
Hi @Maxonvs 
Thanks for the suggestion. I would like to help you but this case has no go, unfortunately.

Page number feature cannot be applied to the reported comments or the correction reports. Due to connection limits, the extension's pagination service can only collect details for questions/answers to generate page numbers. Opening connections for other report types will increase the time of collecting details of reported q/a and will cause to have more unreliable page numbers.

**Comment by seahindeniz** [comment]
I'm closing this request until we have a better, applicable solution to resolve this feature request
