### ISSUE TITLE
There's a bit of a lag while moderating contents at the very bottom of a page of reports.

### ISSUE THREAD

**Issue by Tomboyish44** [seahindeniz/BrainlyTools_Extension#238]
**Describe the issue/bug :**
While scrolling down through many reports and moderating them, it gets pretty laggy while choosing deletion reasons, scrolling, right-clicking, and moderating the content.

**To Reproduce :**
1. Visit the [new mod panel](https://brainly.in/question/add?reported-contents).
2. Scroll down such that more than 372 reports are visible.
3. Click on "✏" and you might experience some lag. 

Profile link [paste below] -->
https://brainly.in/app/profile/2709968

**Comment by seahindeniz** [comment]
Ok so the main problem here is; whenever you scroll, the page tries to show reports by creating these elements, for example
![1e87e402-7a1a-4230-8fe7-70830bbd3d67](https://user-images.githubusercontent.com/5789670/94599051-8be11280-0298-11eb-9842-2514fe0f13cd.gif)

A single element shown in the GIF consumes an **insignificant** amount of memory(RAM). But when the number of elements gets increases, this may result in lots of memory consume that can lead you to have a laggy page.

To solve this, the page will remove report boxes located in the upper/lower side of the viewport/screen when the user scrolls the page. Removal of the elements from the page will decrease the memory usage by freeing the RAM.
But this has a side effect. Users will not be able to use the browser's search tool(CTRL+F) to find texts on the page. Since elements that supposed to contain strings that users may want to find will get removed

**Comment by Tomboyish44** [comment]
Ohh, okay, got it. ✔

Maybe, to prevent this, we can restrict the amount of reports shown in one page? Say the limit of contents displayed in one page is 400, and the moderator will have to shift to the next page to moderate the next 400 reports. [Just a suggestion] 🤔

And, whenever the "LOAD REPORTS" feature is used, the solution you've described above comes to play?
