### ISSUE TITLE
A way to distinguish corrected answers from answers that haven't been corrected in the new mod panel. [Similar to the feature in the old panel]

### ISSUE THREAD

**Issue by Tomboyish44** [seahindeniz/BrainlyTools_Extension#250]
**Describe the issue/bug:**
The feature that was present in the old moderation panel that helped point out corrected answers from answers that haven't been corrected is not available in the new moderation panel.

**To Reproduce:**
1. Visit the [reported contents page.](https://brainly.in/question/add?reported-contents)
2. Click on "CORRECTION REPORTS".
3. You'll be able to see that there isn't a direct way to distinguish corrected answers from answers that haven't been corrected.

**Screenshots [paste below, optional]:**

![image](https://user-images.githubusercontent.com/68370357/94464717-74445400-01dc-11eb-89be-c3ef6c46862b.png)

https://brainly.in/app/profile/2709968

**Comment by seahindeniz** [comment]
When a report gets confirmed, its box is colored with green to understand that it has successfully confirmed. But if extension colors the boxes a bit darker/lighter green on the reports that have corrected, this can lead to confusion.

But since flags are used to show the current status of the reports, the extension will colorize the flag as green for corrected
![image](https://user-images.githubusercontent.com/5789670/94479873-19136100-01de-11eb-8f83-ba1302bf5e50.png)

The blue flag is for correction reports and the green flag is for correction reports that have corrected
