### ISSUE TITLE
Selective deletion on Moderate all

### ISSUE THREAD

**Issue by Happiestwriter012** [seahindeniz/BrainlyTools_Extension#26]
Can we have an option to be able to confirm (if possible to delete) selectively from moderate Panel ( tasks_archivemod)

**Comment by seahindeniz** [comment]
I would like to discuss the scenarios about your request
- Let's say that we have a checkboxes to select reported contents from Moderate all and assume that you have selected. We can't see the whole content of the reported question/answer without opening the moderate panel. Therefore you/others may confirm the content without reviewing it and the content may contains abusive/unacceptable details that you should be removed. What will you suggest at this point?
- Think about the reversed scenarios for the deleting the reported contents. Assume that question/answer may contains acceptable details that you may can't see without opening the moderate panel. What will you suggest at this point?


I've tought about rendering more details about the reported contents to the page- like in the user contents page. But this comes with massive amount of opening requests on other markets. Because on brainly.in, brainly.com or brainly.ph- moderate all serves 12 moderate boxes per page. 
But other markets like the eodev.com has different settings. In the eodev, moderate all serves 450 boxes per page and this may cause delay while rendering the details.

**Comment by Happiestwriter012** [comment]
In all cases, it won't be useful. But if suppose, if there's someone reporting correct answers continously, will be helpful i believe.

And since, it delays on other markets. Never mind, We can stop this request :)
