### ISSUE TITLE
Extension isn't able to detect recent reports while using filters

### ISSUE THREAD

**Issue by HarshSaini800** [seahindeniz/BrainlyTools_Extension#321]
**Describe the issue/bug:**
**Filter Reports** feature in **Reported Contents** doesn't detect reports which were made only some time ago if you try to filter them on the basis of their content using the filters available to sort reports.

**To Reproduce:**
1. Visit [Reported Contents (Beta)](https://brainly.in/question/add?reported-contents)
2. Pick any keyword from the newly reported content and trying using the **contains** filter under **Additional Data** to filter reports with that keyword.
3. The newly reported content doesn't appear in the filtered reports.

**Screenshots:**

![image](https://user-images.githubusercontent.com/67321824/100450926-86f3e000-30dc-11eb-80ce-b05370c3ae25.png)
![image](https://user-images.githubusercontent.com/67321824/100451010-af7bda00-30dc-11eb-9766-064df1f9378d.png)
![image](https://user-images.githubusercontent.com/67321824/100451023-b571bb00-30dc-11eb-8739-3e0ed87bef34.png)

https://brainly.in/profile/CoolestCat015-1426383

**Comment by seahindeniz** [comment]
Hey @HarshSaini800 

You probably need to use the Content filter in order to filter reports by their contents.
![image](https://user-images.githubusercontent.com/5789670/100470184-d50ee080-30e8-11eb-988f-920f2221cde5.png)

The Additional data filter is used to filter reports by their additional data field 
![image](https://user-images.githubusercontent.com/5789670/100470549-7eee6d00-30e9-11eb-8599-7549b9d6656d.png)
