### ISSUE TITLE
Moderação na página inicial

### ISSUE THREAD

**Issue by EtinhoBR** [seahindeniz/BrainlyTools_Extension#341]
Minha ideia é ter possibilidade de remover tarefas em quantidades na página inicial, como é aplicado na parte de "Visualizar conteúdo do usuário".

**Comment by seahindeniz** [comment]
Hey @EtinhoBR 

Thanks for the suggestion. If I understand you correctly, you need a way to remove questions from the feed on homepage, right?

Well, we have considered this ability before and most of us decide that we should have the ability to delete questions one by one with quick delete buttons.
Since the feed is too dynamic, deletion of new questions by selection might be a time consumer for you because some other moderator might also delete the question that you might select and let it in the background to check the next one, you know. Your selections might get for nothing when that happens 😓

**Comment by EtinhoBR** [comment]
Olá @seahindeniz!

Realmente pode ter este problema.
Gostaria também comunicar um possível problema que tenho a usar a extensão: Eu tenho a permissão de remover todas as tarefas de um usuários de vez, só que com a extensão ligada essa opção não aparece, somente quando eu desativo a extensão e recarrego o site.

Sem a extensão:
![image](https://user-images.githubusercontent.com/76266607/102700476-84446080-422c-11eb-8372-65f5d431938d.png)

Com a extensão:
![image](https://user-images.githubusercontent.com/76266607/102700491-a4741f80-422c-11eb-8a55-b72e08cffcae.png)

**Comment by HydroXBR** [comment]
@EtinhoBR 

All right? In that case, I think you would have to open a new problem, as it is another matter ;)
