### ISSUE TITLE
Display problem when changing the density on the Reported Contents page

### ISSUE THREAD

**Issue by tom-rh** [seahindeniz/BrainlyTools_Extension#364]
**Describe the issue/bug:**

Display problem when changing when the density is greater than or equal to 7.
The buttons at the top right slide to the right.

**To Reproduce:**

1. Go on Reported Contents page.
2. Increase the density.

**Screenshots [paste below, optional]:**

![Issue](https://user-images.githubusercontent.com/64775524/103812853-6f0a6700-505f-11eb-8c39-f46410862dcb.gif)

https://nosdevoirs.fr/profil/TomRh-578978

**Comment by seahindeniz** [comment]
Interesting

**Comment by seahindeniz** [comment]
Well, that's actually normal because the page cannot squeeze elements more than that and therefore, it forces elements to be rendered outside the view box.

As a solution, I have made some changes on some container elements to wrap elements like this:
![image](https://user-images.githubusercontent.com/5789670/103884560-d243da00-50ef-11eb-8a52-06cdf4b27c90.png)
