### ISSUE TITLE
Users section returning error 410

### ISSUE THREAD

**Issue by Alphka** [seahindeniz/BrainlyTools_Extension#387]
**Describe the issue/bug:**
When you open a question made by a user who got his account deleted, the "Users section" returns an error

**To Reproduce:**
1. Go to a question made by a deleted account, like [this one](https://brainly.com.br/tarefa/6559408)
2. Open console to see the error

![image](https://user-images.githubusercontent.com/71673694/104792052-d620cd80-577b-11eb-90ef-169c8440e418.png)

[https://brainly.com.br/perfil/Alphka-14558160](https://brainly.com.br/perfil/Alphka-14558160)

**Comment by seahindeniz** [comment]
Hi @Alphka,

This issue is kind of related to Brainly. When you visit that users profile page, you will also get an 410 error, and we can't have a solution for this one unfortunately. However, I have noticed that the loading icon is spinning even after receiving an error response from Brainly. I think removing the loading icon will at least satisfy the need.
