### ISSUE TITLE
The shortcut "go to old profile" doesn't work

### ISSUE THREAD

**Issue by Maxonvs** [seahindeniz/BrainlyTools_Extension#402]
**To Reproduce:**
1. Go to a profile page
2. Click to view the new profile
3. Try to click to view old profile page

https://brainly.com.br/app/profile/1110038

**Comment by Alphka** [comment]
This happens because of the "/answers" and "/questions" at the end of the URL
![image](https://user-images.githubusercontent.com/71673694/109374902-6f70f280-7897-11eb-8a5f-a7a9fdb0ec6d.png)
![image](https://user-images.githubusercontent.com/71673694/109374909-7e57a500-7897-11eb-82fb-423564274063.png)
