### ISSUE TITLE
The Move Buttons Are Unable To Move To The Next Moderation Page

### ISSUE THREAD

**Issue by ArcelBrainly** [seahindeniz/BrainlyTools_Extension#90]
HI ! When i try to moderate this issue keeps happening again and again in different moderation panel with the extension. I am unable to switch between different moderation tabs it gets hanged or stuck. This keeps on happening every time at the end I have to refresh the page in order to be able to moderate again.It gets stuck and you are unable to do anything in the moderation tab.

Here is the detailed video describing the issue. Please have a look:

https://drive.google.com/file/d/1S3pMkn4QY3yEFfrWB90g2m0kNvrddhdo/preview

**Comment by seahindeniz** [comment]
Got it!
Tools that enhances mod all page needs to be reconstructed. In the next release, the tools will be in BETA stage

**Comment by ArcelBrainly** [comment]
Great ! Good job

**Comment by seahindeniz** [comment]
I will close this issue because I have found the exact cause of this problem which is related to Brainly and it's already been reported to them.
For example, https://brainly.in/question/11362775 this question has a response that contains Latex contents init and this fails browser to parse the content. Therefore, moderation panel can't continue to moderate.

I can't fix this issue directly but I can probably find a workaround to close the failed moderation panel at least.
